ギブアップ機能の機能追加
kitazawasyogo/HitAndBlow pull request #13
Opened 2023-02-16 01:58 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

**ギブアップ機能の機能追加を行いました。**

不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-02-16 02:17 UTC, nabemasamasa reviewed
done

2023-02-16 02:17 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.ToLower().Equals("giveup") Then
[nits] 入力値に対して、小文字大文字区別せず「giveup」が入力されたらGiveUpであることを検証するテストがほしい。。。。
小文字大文字区別しないんだから、全部小文字、全部大文字、小文字大文字混在、でテストしてギブアップと判定できてること、あとは文字列不一致、のパターンが検証出来てればいいかな。

2023-02-16 02:17 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Dim inputArray As Char() = {"0", "0", "0", "0"}
MainモジュールがHitAndBlowGameクラスのGetInputValueメソッドの初期値を知っているのが嫌です。
(マジックナンバー的ですし、カプセル化したい……)

[IMO] HitAndBlowGameに`IsExitGame`というプロパティを持たせて、それで１ゲームを終了するべきか判断するようにできませんか？

2023-02-16 02:17 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +                    ShowAnswer(correctArray)
正解表示するメソッド呼び出して、コードの再利用 👍

2023-02-16 02:17 UTC, Takatatsu9 reviewed
Done

2023-02-16 02:17 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +                Exit Sub
[Q] なんで入力値と入力配列が一致するとメソッドを抜けるんですか？

2023-02-16 02:17 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
ヒットアンドブローRTAはーじまーるよー
早速スタートです
最速で0000を入力します
「もう一度遊びますか？」が表示された瞬間タイマーストップ！
記録は1.78秒！

2023-02-16 03:11 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +                Exit Sub
メソッドを抜ける方法がこの方法しか思い浮かびませんでした。

https://github.com/kitazawasyogo/HitAndBlow/pull/13#discussion_r1107934994 こちらの頂いたコメントのようにHitAndBlowGameにIsExitGameというプロパティを持たせて、それで１ゲームを終了するべきか判断する方法に変更いたします。

2023-02-16 07:04 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Dim inputArray As Char() = {"0", "0", "0", "0"}
①`IsExitGame`という名前の指定があり、`Is～`なのでおそらくBooleanのプロパティを設定する
②IsExitGame（Boolean変数）で初期値はFalse
③`giveup`の場合は初期値FalseのIsExitGameプロパティの値をtrueに変える
④Mainモジュールで`IsExitGame`の`true`OR`False`を判定する

以上の対応にいたします。
`IsExitGame`プロパティを使用すればhttps://github.com/kitazawasyogo/HitAndBlow/pull/13#discussion_r1107933186 理由がなく回答できなかったこちらのコメントの内容も解決できると考えています。

2023-02-16 07:44 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Dim inputArray As Char() = {"0", "0", "0", "0"}
実装する前に、予め確認の実装方針のコメント 👍 

②で「変数」と言っているのだけ気になりました。
外部から操作出来たりするとカプセル化の意味がないのでちゃんとReadOnly Propertyで実装してほしいです。
そこだけ補足です。
他は、良いと思います。

2023-02-17 04:39 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +                Exit Sub
変更したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/2578e097668d5bd8f9ed2967e30af866bbfbf2dd

2023-02-17 04:39 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Dim inputArray As Char() = {"0", "0", "0", "0"}
変更したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/2578e097668d5bd8f9ed2967e30af866bbfbf2dd

2023-02-17 04:40 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.ToLower().Equals("giveup") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/b94c5ce242b692a1484652024aa0b89a261a738a https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/cbd9a7cea12122a9dba721d52a041af082cad1da

2023-02-17 04:41 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行いました。
レビューお願いいたします。

2023-02-17 04:48 UTC, Takatatsu9 reviewed
Done

2023-02-17 04:48 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Dim giveUpJudgement As Boolean = game.IsExitGame()
[MUST] Boolean型は

2023-02-17 04:48 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.Equals("giveup") Then
> ギブアップの入力値のテストを行う為入力値を全て小文字にする機能をメソッド抽出

[IMO] なんか全体的にロジックが冗長すぎる、無駄が多く感じる。
「入力値を渡したらあとはギブアップ用の入力値か判定するメソッドがやってくれる」にまとめるならまだわかるけど、
これだと「無駄な処理を大量に経由させると、文字列を小文字にするだけのメソッドにたどり着く権利が得られる」を追加しただけだなぁ。

2023-02-17 04:48 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ギブアップの入力値が全て大文字だった場合小文字に変換された値を返す()
> ギブアップの入力値をテストするメソッドの追加

[IMO] テストはテスト対象が追加されたコミットに混ぜるようにしてください。
なぜだかわかりますか？

2023-02-17 04:50 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.ToLower().Equals("giveup") Then
> あとは文字列不一致でギブアップじゃないよ、のパターン

こちらのテストパターンは行えませんでしたが[nits] コメントですのでPushさせて頂きました。

2023-02-17 04:58 UTC, nabemasamasa requested changes, later dismissed
コーディングルール違反

2023-02-17 04:58 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Private IsExitHitAndBlow As Boolean = False
[MUST] 惜しい、実装は合ってるんですが、Private変数は頭小文字です。
そのクラスの外部から参照できる変数が頭大文字で、それ以外は小文字でわかりやすくしています。

2023-02-17 04:58 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            If giveUpJudgement Then
[nits] …直接`game.IsExitGame`なら`Exit Sub`していい気がする。
変数化したことによって、ギブアップ時だけしか使えないよって狭めちゃってるし、
後、Boolean変数のルールにも実は違反してない？  => [knowledge/VB.NET.コーディングルール.md#22-boolean変数](https://github.com/daniel-software-tokyo/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#22-boolean%E5%A4%89%E6%95%B0)

2023-02-17 04:58 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Public Function ConvertLowErcase(inputValue As String) As String
[Q] Summaryコメントは「ギブアップの入力値を全て小文字にする」けどメソッド名「ConvertLowErcase」。
まず、アッパーキャメルで大文字にする箇所間違ってない？
Summaryコメントとメソッド名、一致してます？

2023-02-17 05:01 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.ToLower().Equals("giveup") Then
[imo] ユーザーの入力文字に対してギブアップかどうか判定するだけの戻り値Booleanのメソッドにすれば、文字列不一致でギブアップじゃないよ(=False)のパターンもテストできませんか？

2023-02-17 05:08 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ギブアップの入力値が全て大文字だった場合小文字に変換された値を返す()
https://github.com/kitazawasyogo/HitAndBlow/commit/b94c5ce242b692a1484652024aa0b89a261a738a https://github.com/kitazawasyogo/HitAndBlow/commit/cbd9a7cea12122a9dba721d52a041af082cad1da のコミットはまとめ、強制プッシュいたします。
次回以降テストはテスト対象が追加されたコミットに混ぜるよういたします。

どのテスト対象に対してテストが追加されたか分かりやすいからでしょうか？

2023-02-17 05:13 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ギブアップの入力値が全て大文字だった場合小文字に変換された値を返す()
それもありますが、機能の追加と同時に正しく動作することを保証するためです。

なんか、なんでもかんでも「わかりやすい」で片付けようとしてるように見えますが…
「レビューしやすいコード」だけじゃなくて、
「正しく動作すること」「保守しやすい（読みやすい、理解しやすい）コードであること」も重要です

2023-02-17 05:42 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ギブアップの入力値が全て大文字だった場合小文字に変換された値を返す()
機能追加と同時にテストも書けば、以降のコミットで干渉するコードを修正しても、仕様が満たされ続けている事を簡単に確認でき、安心して修正する事ができます。
往々にしてあるのが、コードを修正する事で想定していなかった機能まで壊れてしまった、という「デグレ」ですが、テストを追加しておけば自動テストで常に全部チェックしてくれるのでデグレに気づきやすくもなります。

テストがない、追加されないプロジェクトというのは、全部人力で動作確認してチェックしている証左でもあるので、デグレが発生しやすいです。

2023-02-17 06:59 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +    Public Function ConvertLowErcase(inputValue As String) As String
・アッパーキャメルで大文字にする箇所間違えていました。「ConvertLowercase」が正しい大文字の箇所です。
・Summaryコメントとメソッド名一致させる為修正いたします。
　　Summaryコメント：「ギブアップの入力値を全て小文字にする」
　　メソッド名：「ConvertLowercaseGiveUpInputValue」

2023-02-17 07:06 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Public Function ConvertLowErcase(inputValue As String) As String
まぁ、これはIMOなんですが、
https://github.com/kitazawasyogo/HitAndBlow/pull/13#discussion_r1109306372 のコメントを取り入れてそこにこのメソッドでやってる処理を移譲すれば、そもそもこのメソッド自体いらなくなるかもよ？

2023-02-17 08:03 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行いました。
https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/a7cf865f484d6c767741185b78d5bf07bbd0599e こちらのコミットから未レビューです。レビューお願いいたします。

2023-02-17 08:05 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ギブアップの入力値が全て大文字だった場合小文字に変換された値を返す()
ご指摘ありがとうございます。
まとめたコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/80adf7dd51f4dcd5cbacec099d7b202d54128998

2023-02-17 08:07 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If giveUpJudgement Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/a7cf865f484d6c767741185b78d5bf07bbd0599e

2023-02-17 08:09 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Dim giveUpJudgement As Boolean = game.IsExitGame()
変数を使用しない方法に変更しました。
次回以降Boolean型変数の命名規則の違反が無いようにいたします。

対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/a7cf865f484d6c767741185b78d5bf07bbd0599e

2023-02-17 08:10 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.ToLower().Equals("giveup") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/f4c18b32b4afa8e4134d4d0dd8f5ec08ac46aff8

2023-02-17 08:10 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +                ElseIf input.Equals("giveup") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/f4c18b32b4afa8e4134d4d0dd8f5ec08ac46aff8

2023-02-17 08:10 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +    Private IsExitHitAndBlow As Boolean = False
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/f8ad2a3f27499359fcde07d1c9759d06ac15283b

2023-02-17 08:40 UTC, nabemasamasa reviewed
Done

2023-02-17 08:40 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim isExitInputValue As Boolean = False
……………ClassicASPとかVBSとかVB6とかVBAとかで見る、超超超前時代的なFunctionの戻り値の設定方法を思い浮かべる……………………つらい………………
[nits] VB.NETはReturnで値を返せるんですから、変数経由せず戻り値を直接Returnする方がいいな。
というか、Equalsの結果をそのまま返すんじゃダメなんです？
なんなら、`(inputValue.ToLower()).Equals("giveup")`でも`String.Equals(inputValue,"giveup", OrdinalCase?)`でも良くない？とは思う。(確か、String.Equalsの第三引数でそういうルールで比較するか選べたはず)

2023-02-17 08:40 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Public Function IsExitHitAndBlowGame(inputValue As String) As Boolean
[imo]個人的には「ギブアップかどうか」だけ判定させたいから「IsExit」よりも「IsGiveup」の方がいい(てか、Summaryコメントとメソッド名ちぐはぐだし)

2023-02-17 08:40 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Dim isActual As Boolean = gameTest.IsExitHitAndBlowGame(inputTestValue)
言い忘れてた、テストクラスの`actual`は別にルール違反してても大丈夫。

2023-02-17 08:40 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ギブアップの入力値が文字列一致で全て小文字だった場合Trueを返す()
「XXXの場合OOOを返す」構文、条件と結果が一目でわかって 👍 よね

2023-02-20 00:16 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Dim isActual As Boolean = gameTest.IsExitHitAndBlowGame(inputTestValue)
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/10428cb788652eaa4274ade02e4b990dc98f4d48

2023-02-20 00:16 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +    Public Function IsExitHitAndBlowGame(inputValue As String) As Boolean
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/5e396a332cb05aba0b9b462f53cc9110a305ed01

2023-02-20 00:17 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim isExitInputValue As Boolean = False
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/04cf8e34fceb0f1c2fb8517aeedc9d5f7f4b6cc2

2023-02-20 00:17 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いましたのでレビューお願いいたします。

2023-02-21 01:00 UTC, nabemasamasa reviewed
Done

2023-02-21 01:15 UTC, Takatatsu9 reviewed
Done

2023-02-21 01:15 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Dim isActual As Boolean = gameTest.IsExitHitAndBlowGame(inputTestValue)
actualって「実際」って意味なんで、isつけたら「実際か？」って意味不明な言葉になりますよ

2023-02-21 01:15 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        Return False
[IMO] `inputValue.ToLower().Equals("giveup")`がBoolean返す処理なので、
このコードだとやってることは実質下記と同じです
```
Dim result As Boolean = inputValue.ToLower().Equals("giveup")
If result = True Then
    Return True
ElseIf result = False Then
    Return False
End If
```
もっとシンプルに書く方法がありそうですね

2023-02-21 02:05 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Return False
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/97651470ca311812c5f816770ed12647398e2ecf

2023-02-21 02:05 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いましたのでレビュー宜しくお願いいたします。

2023-02-21 02:13 UTC, Takatatsu9 reviewed
Done

2023-02-21 02:13 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        Return isGiveUp
[Q] もしかしてReturnは必ず変数化した値じゃないと返せないと思ってます？

2023-02-21 02:17 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Return isGiveUp
思っていました。

`Return inputValue.ToLower().Equals("giveup")`
変数化も必要ないことに気に気づきました。こちらに変更いたします。

2023-02-21 02:19 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Return isGiveUp
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/13/commits/f0b723d5535748c8fe4f02e5896fba5f81f6ab11

2023-02-21 02:22 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いましたのでレビュー宜しくお願いいたします。

2023-02-21 02:22 UTC, Takatatsu9 reviewed
Done

2023-02-21 02:30 UTC, nabemasamasa reviewed
Done 👍

2023-02-21 02:35 UTC, kitazawasyogo commented
お忙しい中レビューありがとうございます。
コミットの整理を行い強制プッシュしました。[変更点](https://github.com/kitazawasyogo/HitAndBlow/compare/f0b723d5535748c8fe4f02e5896fba5f81f6ab11..130a8cfa20f232168753dd16f3d77f279ee21b0e)はございません。

マージいたします。

2023-02-21 02:37 UTC, merged

2023-02-21 05:53 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
そういえば今更すぎるんですけど、このRTAやったときにやめる際
小文字で`n`入力したら弾かれたんですけどそういう仕様でしたか？

2023-02-21 06:00 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
Y/N完全一致でないと弾かれます。
`もう一度遊びますか？(Y/N)：`という指定の表示する文言の中に入力値の指定があったので仕様確認の際に（Y/N）の大文字、小文字の許容について確認は行いませんでした。

2023-02-21 06:01 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
Y/N完全一致でないと弾かれます。
指定の表示する文言「もう一度遊びますか？(Y/N)：」の中に入力値の指定があったので仕様確認の際に（Y/N）の大文字、小文字の許容について確認は行いませんでした。

2023-02-21 06:13 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
どういう実装になっているかじゃなくて仕様通りか聞きたいわけででしてね・・・。
そして「確認は行いませんでした」で話を切っているということは、今後確認する予定は無いってことですね？

2023-02-21 07:03 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
質問に対して適切な回答でなく、失礼しました。

> （まあ、別にこういう細部は突っ込まれなきゃそのままでもいいと思うけど）

修正する必要がなく仕様確認する必要もないと個人的に考えています。
指摘がありましたら仕様確認、変更を行わせて頂きます。

2023-02-21 07:42 UTC, takas-ho commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
[Q] なかなか酷いなぁ
- 大文字しか判定しないのは、ユーザーが使いやすいですか？嬉しいですか？
    - @kitazawasyogo は自分で動作テストしててなんとも思わなかったんですか？ 

言われたことしか実装しない、っていうのはコーダーの仕事だと思います。プログラマーじゃない

2023-02-21 07:57 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
・大文字しか判定しないのは、「もう一度遊びますか？(Y/N)：」というhttps://github.com/kitazawasyogo/HitAndBlow/issues/1#issuecomment-1409661582 仕様の指示に合わせる為です。
・動作テストしていて小文字も許容されたら楽だと思いましたが仕様に合わせる事を優先しました。

2023-02-21 08:15 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
使いづらい、仕様の確認が不足しているかもしれないと分かった時にremottyなどで確認する必要がありました。
失礼しました。

2023-02-21 08:17 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
使いづらいと思った時にremottyなどで確認する必要がありました。
失礼しました。

2023-02-21 22:56 UTC, takas-ho commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
もう一度

[Q] 大文字しか判定しないのは、ユーザーが使いやすいですか？嬉しいですか？

2023-02-22 00:18 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If inputValue = inputArray Then
大文字しか判定しないのは、ユーザーが使いづらく、嬉しくありません。