挑戦桁数を変更できるようにする機能の追加
kitazawasyogo/HitAndBlow pull request #17
Opened 2023-02-27 02:33 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

**挑戦桁数を変更できるようにする機能の追加を行いました。**

不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-02-27 04:34 UTC, Takatatsu9 reviewed
Done

2023-02-27 04:34 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +            Assert.That(ex.Message, [Is].EqualTo("入力値が5桁の数字ではありません"))
[IMO] これは既存のテスト内容の書き換え（1つ廃止して1つ新規追加）じゃなく、
残しつつ追加するほうがいいな。
```vb
<TestCase(1, 2, 3)>
<TestCase(4, 5, 6)>
Public Sub テスト(arg1 As Object, arg2 As Object, arg3 As Object)
```
って書けば同じテストコードで複数のテストパターン書けます。
あとサンプルでこういう書き方してるだけなので、引数名や型はちゃんと見合ったもの使ってくださいね。

2023-02-27 05:15 UTC, nabemasamasa reviewed
done

2023-02-27 05:15 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim arrayMaxLength As Integer = Integer.Parse(digits) - 1
[imo] indexで使用する上で不都合だから`-1`するなら、MaxLengthという変数名は違うと思う。(10ケタなのにMaxLengthに9が入ることになる)
`MaxIndex`にするか、もしくは`For....To arrayMaxLength - 1`にした方が命名に整合性が取れる

2023-02-27 05:15 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <param name="correctValue">正解の値</param>
引数増やしたなら、メソッドのコメントも同期したいな

2023-02-27 05:15 UTC, nabemasamasa commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
[Q] なんでここ、メソッド名`IsXXXX`でBoolean返してるはずなのに、String型の変数に代入して型の不一致エラーになってないんでしょう…？

2023-02-27 05:15 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Private Function ValidateInputDigitsValue(input As String) As Boolean
[Q] テスト追加できませんか？

2023-02-27 06:01 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +    Private Function ValidateInputDigitsValue(input As String) As Boolean
MainとHitAndBlowクラスにある値のチェックを行うメソッドを、新しく作成したクラス（入力値のチェックを行う為のクラス）にまとめテストを行えるようにします。

2023-02-27 06:04 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
Booleanの値をString型に変換したことが間違いであることは分かりますが、なぜ型の変換も行わずに代入してしまったのに型の不一致エラーになってないのか分かりません。

inputValue の型をString型ではなくBooleanに修正し変数名も変更いたします。

2023-02-27 06:13 UTC, nabemasamasa commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
HitAndBlowプロジェクトのコンパイルの設定はどうですか？
VBAとか、VBファイルひとつ単位で設定するなら、Option Strict Onで型厳密じゃないとエラーに出来るんですが…

2023-02-27 06:21 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
HitAndBlowプロジェクトのコンパイルのOption Strict がOffになっていました。
Onに変更しコミットいたします。

2023-02-27 06:24 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
プロジェクト作成時の初めに毎回Onに変更した方が良いのでしょうか？

2023-02-27 06:44 UTC, nabemasamasa commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
はい、OnじゃなかったらOnにしてほしいです。課題以外でもOnにする事を推奨します。
暗黙的な型変換、例えばInteger型に数値以外のStringを代入しようするコードを書いてしまう、といったことを実行時時点でなくコードを書いてるときに気づけます。
コードが大規模になればなるほど、管理しきれなくなっていくので早めの設定が大事です。

2023-02-28 01:31 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いました。

レビューお願いいたします。

2023-02-28 01:32 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +            Assert.That(ex.Message, [Is].EqualTo("入力値が5桁の数字ではありません"))
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/e70981f113603034b360e93dfcf4db265c8556e1

2023-02-28 01:32 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim arrayMaxLength As Integer = Integer.Parse(digits) - 1
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/701ed29321bf1c8fa8cecdf76e0f9c889e6faa47

2023-02-28 01:32 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <param name="correctValue">正解の値</param>
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/3fed442b37dc849439399299beeae7a0b14cff49

2023-02-28 01:32 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/07e588abc633664387338ff8f33071e597c21b24

2023-02-28 01:34 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
>              Dim inputValue As String = IsJudgementReplayAnswer()
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/07e588abc633664387338ff8f33071e597c21b24 https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/e6f24ba2ba1e61acbaf39718fdbea45a1a8a820a https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/3fbeba82ae3ac35da704020532451b23a0395ea1

2023-02-28 01:34 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +    Private Function ValidateInputDigitsValue(input As String) As Boolean
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/cdb90f8386ed81c8048e92675対応したコミットはこちらです：

2023-02-28 04:19 UTC, nabemasamasa reviewed
doe

2023-02-28 04:19 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
[Q] OptionInferをOffにすると何がうれしいんですか？

2023-02-28 04:19 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
これは、直前に含まれているべきコミットだと思う。なぜなら、コンパイルエラーになるコミットになっちゃうから。
コンパイルエラー、テストがコケるコミットを作らない為には、
プロジェクトの設定を変える前に修正コミットをするか、プロジェクトの設定を変更する際に合わせてコンパイルエラーになるコードを修正するか、の二択。

2023-02-28 04:19 UTC, nabemasamasa commented on HitAndBlowTest/JudgementInputValueTest.vb
> +    <Test()> Public Sub 挑戦桁数の入力値が数字以外の場合例外を投げる()
[imo] 異常系のテストはしっかりテスト出来てると思うんだけど、正常系のテストも欲しいです！

2023-02-28 04:19 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub 正解の値の桁数が入力された挑戦桁数になっているか(inputDigitsValue As String)
[imo] `<Test>`なくても`<TestCase()>`だけでも、ちゃんとUnitTest動いてくれるよ。

2023-02-28 04:19 UTC, nabemasamasa commented on HitAndBlow/JudgementInputValue.vb
> +        Dim displayDigitsNumber As Integer = Integer.Parse(digitsNumber)
[nits] 今更だけど、「挑戦桁数」はInteger型で使いまわせるほうがよかったね……。
毎回、Integer.Parseしてて「入力桁数を返す」メソッドの戻り値からずっとIntegerだったらInteger.Parseいらなかったんだろうなぁ…とか思っちゃう。

2023-02-28 04:24 UTC, Takatatsu9 requested changes
Done

2023-02-28 04:24 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not correctArray.Contains(Char.Parse(randomCorrectValie)) Then
> Option-Strict/Onでは暗黙的な変換が許可されていない為修正

[Q] このコミットは1つ前の`一致しない型の代入を見逃さない為にコンパイルの設定を変更`と
別なので、エラーにはなっていなかった（警告が出るだけでビルドは通る）という認識でよろしいですか？

2023-02-28 04:24 UTC, Takatatsu9 commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
[nits] このクラス名を日本語にすると「入力値の判定」でメソッド名めいた名前だから合わないと思うな。
チェックするために使うValidateメソッドを色々突っ込んでるクラスだし、
そうだな……「入力値を検証するもの！」という意味の`InputValueValidator`というのはどうかな！

2023-02-28 04:24 UTC, Takatatsu9 commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
[MUST] `Public`

2023-02-28 04:50 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
Option InferをOffにすると、ローカル変数の型の推論が無効となるので、As句を省略して推論で変数を宣言することができなくなります。

意図せず行ってしまった変更でPush前の確認の際も気付きませんでした。失礼しました。

OptionInferはOnにし、必ずAs句で型を定義した方が型の定義の際に間違ったコードを書いてしまう事を防げるのでOnに戻させていただきます。

2023-02-28 04:50 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
プロジェクトの設定を変えた後、コードの修正が必要なことに気づき修正を行いコミットをまとめる作業を忘れてしまいました。

プロジェクトの設定を変更する際に合わせてコンパイルエラーになるコードを修正するよう、コミットをまとめ合わせえてコミットコメントも修正いたします。

2023-02-28 04:53 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not correctArray.Contains(Char.Parse(randomCorrectValie)) Then
エラーになっており、エラーの起こるコミットをPushしてしまいました。
失礼しました。

`一致しない型の代入を見逃さない為にコンパイルの設定を変更`と`Option-Strict/Onでは暗黙的な変換が許可されていない為修正`のコミットを一つのコミットにまとめコミットコメントを修正する作業を忘れてしまいました。
修正いたします。

2023-02-28 04:56 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not correctArray.Contains(Char.Parse(randomCorrectValie)) Then
コミットコメントを書く段階で自分でハッキリ認識しているはずなので
明らかに見逃すはずが無いと思うんですけど？

2023-02-28 05:06 UTC, kitazawasyogo commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
すみません。こちらのコメントで修正すべき点が理解できていません。
お手数をおかけしますが具体的に何を修正すれば良いか教えていただけますでしょうか。

2023-02-28 05:27 UTC, Takatatsu9 commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
色々言いたいことはありますけど、1回だけ耐えることにします。
ヒントを与えます。今まで何度も指摘してきたことです。
**今までレビューで指摘されたことをきちんと覚えていれば、思い当たること**です。

2023-02-28 05:47 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
なるほど、デメリットしかないと、了解です。
では、修正をお願いします。

2023-02-28 05:51 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
よくわかってないんだけど、プロジェクトの設定を変えた後、すぐコミットしたって事？

1. 気づかずInferを弄ってしまう(On→Off)
2. StrictをOff→On
3. コミット
4. ビルドしたらなんかエラーになる
5. コードを修正してコミット

って事？

2023-02-28 06:08 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
その通りです。
プロジェクトの設定を変えた後ビルド確認せずにコミットしてしまいました。

2023-02-28 06:21 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
把握です。ついコミットを逸る気持ちはわからなくもないけど、最終的には「ビルドが通る」「テストが動く」コミットにするルールなので、急く気持ちを抑えてテスト通る事確認してからコミットするように、注意してください。(初めの頃に一度あった気もする)

2023-02-28 06:22 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
あ、その「注意」はそれはそれとして、以下は以下で対応お願いします。

> プロジェクトの設定を変更する際に合わせてコンパイルエラーになるコードを修正するよう、コミットをまとめ合わせえてコミットコメントも修正いたします。

2023-03-01 01:02 UTC, kitazawasyogo commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
`Validator`という単語がクラス名に適切（クラスの役割がクラス名から読み取れる）だと思いました。
クラス名`InputValueValidator`に変更いたします。

2023-03-01 01:02 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not correctArray.Contains(Char.Parse(randomCorrectValie)) Then
`一致しない型の代入を見逃さない為にコンパイルの設定を変更`のコミットを作成した際、デバック実行テストを怠ってしまいました。
その後エラーが起こっていて、`一致しない型の代入を見逃さない為にコンパイルの設定を変更`がコンパイルエラーになるコミットになってしまっていることに気が付き、エラーの修正を行いコミットしました。`Option-Strict/Onでは暗黙的な変換が許可されていない為修正`

・デバック実行の確認をせずコンパイルエラーになるコミットにしてしまった
・コンパイルエラーになるとその後コンパイルエラーを修正したコミットをPushする前にまとめることを忘れてしまった
事が原因です。
今後同じことが無いよう改めさせて頂きます。

2023-03-01 01:04 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
https://github.com/kitazawasyogo/HitAndBlow/pull/17#discussion_r1119619669
前にも一度ご指摘頂いたにもかかわらず同じミスをしてしまい失礼いたしました。
今後同じことが無いよう改めさせて頂きます。

対応いたします。

2023-03-01 01:04 UTC, kitazawasyogo commented on HitAndBlowTest/JudgementInputValueTest.vb
> +    <Test()> Public Sub 挑戦桁数の入力値が数字以外の場合例外を投げる()
レビューありがとうございます。
正常系のテスト追加いたします。

2023-03-01 01:36 UTC, kitazawasyogo commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
コメント追加いたします。

メソッドや変数のコメントだけでなく`クラスにもコメント必要`という事を忘れてしまっていました。
失礼いたしました。

2023-03-01 01:41 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not correctArray.Contains(Char.Parse(randomCorrectValie)) Then
じゃあ次から忘れないようにfixupする前提のコミットはfixupコミットで作ってください。

2023-03-01 02:18 UTC, kitazawasyogo commented
レビューありがとうございます。



ご指摘頂いた部分の修正を行いました。
https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/c13472236ae6e3e946756389c80085edffa242e1 こちらのコミットのレビューと、
https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/f95bcce8680c2221758d62264b4eb0ecf71b9b30 から未レビューですのでレビューお願いいたします。

2023-03-01 02:19 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlow.vbproj
> +    <OptionInfer>Off</OptionInfer>
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/f95bcce8680c2221758d62264b4eb0ecf71b9b30

2023-03-01 02:19 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim randomCorrectValie As String = randomValue.ToString
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/c13472236ae6e3e946756389c80085edffa242e1

2023-03-01 02:19 UTC, kitazawasyogo commented on HitAndBlowTest/JudgementInputValueTest.vb
> +    <Test()> Public Sub 挑戦桁数の入力値が数字以外の場合例外を投げる()
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/d876e75e45a34851aff977b9c8a94189406cc75d

2023-03-01 02:20 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub 正解の値の桁数が入力された挑戦桁数になっているか(inputDigitsValue As String)
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/ae4c443541d6e15f1d388c61515ccb50d9a40328

2023-03-01 02:20 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not correctArray.Contains(Char.Parse(randomCorrectValie)) Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/c13472236ae6e3e946756389c80085edffa242e1

2023-03-01 02:20 UTC, kitazawasyogo commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/26606e8c13c91d3afd3bcce66fa69de34342f07e

2023-03-01 02:20 UTC, kitazawasyogo commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/fb307487dd516f85e2b3fd8f4d3e2079bf202868

2023-03-01 03:12 UTC, nabemasamasa reviewed
done

2023-03-01 03:12 UTC, nabemasamasa commented on HitAndBlowTest/JudgementInputValueTest.vb
>  Public Class JudgementInputValueTest
テストクラス名のRename漏れてます。

2023-03-01 03:12 UTC, nabemasamasa commented on HitAndBlowTest/JudgementInputValueTest.vb
> +''' </summary>
過去の指摘で言い忘れてたらごめんだけど、 テストクラスは別にコメント無くてもよかったはず。

コーディングルールとしてコメント必須にしている目的としては、開発者が他のクラスからとあるクラスを使いたい時にコメントがないとクラス名からエスパーしたり実装を見なくちゃいけなくて不親切なのと、(忘れてたんだけど)納品資料を作ろうとして解析ツールにかけた時にコメントがないと不十分な資料が出来てしまう事。
外部から利用されないテストクラスはその目的の範囲外なのと、納品資料を作る際にはテストプロジェクトは提出対象外なので、別にテストクラスはコメントがなくても良い。

2023-03-01 03:19 UTC, nabemasamasa commented
今回のようなケースのForcePushの場合は、Fixupのコミット整理時にForcePushして、指摘対応分は追加でPushしてほしかったです……。
何故なら、ForcePushした際には以下のリンクや`[compare]`でForcePush前後の差分を見れますが、指摘対応分の差分まで混ざってしまうと本当にレビュー済みの内容とForcePush後とで差分がないか不安になるからです。。。
![image](https://user-images.githubusercontent.com/20126608/222035838-b2cc234c-3af7-4f11-9312-490916c02836.png)


あと、 https://github.com/kitazawasyogo/HitAndBlow/commit/c13472236ae6e3e946756389c80085edffa242e1 について、どこがどう変わったか、もあるとその内容だけレビューできるので助かります。

2023-03-01 04:19 UTC, kitazawasyogo commented on HitAndBlowTest/JudgementInputValueTest.vb
> +''' </summary>
コメントを書く目的と、テストクラスにはコメントが無くても良い理由について理解しました。
不要なコメント削除しておきます。

2023-03-01 04:26 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/HitAndBlow/pull/17#issuecomment-1449273856 
次回以降差分が見れるようにForcePushし、どこがどう変わったかも含めてコメントするように致します。

2023-03-01 04:27 UTC, kitazawasyogo commented on HitAndBlowTest/JudgementInputValueTest.vb
>  Public Class JudgementInputValueTest
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/81ef692513db4b8e97f69ede99157af1fe5f3f0b

2023-03-01 04:27 UTC, kitazawasyogo commented on HitAndBlowTest/JudgementInputValueTest.vb
> +''' </summary>
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/17/commits/5b950ce3c41bacf61be2c03bd9b1c8939628360d

2023-03-01 04:28 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いましたのでレビューお願いいたします。

2023-03-01 05:10 UTC, nabemasamasa reviewed
Done

2023-03-01 05:10 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="InputValueValidator.vb" />
ファイル名も変わってなかったんか……気づかなかった

[imo] VisualStudioで`Ctrl+R, Ctrl+R`でRename出来るんですが、それならクラスをRenameした際にファイル名も追従してくれました。今後の参考に。

2023-03-01 05:16 UTC, nabemasamasa commented on HitAndBlowTest/JudgementInputValueTest.vb
>  Public Class JudgementInputValueTest
雑。

2023-03-01 05:17 UTC, Takatatsu9 commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
必ずではありませんが、できるだけ書くべきです。
そして、あなたはその「できるだけ書くべき」だってことを知りませんでしたよね。
ならば今は「"できるだけ書くべき"だということを覚えるために、"必ず書く"べし」だと言っておきます。

2023-03-01 05:22 UTC, kitazawasyogo commented on HitAndBlow/JudgementInputValue.vb
> +Public Class JudgementInputValue
コメントありがとうございます。
今後書くように致します。

2023-03-01 05:24 UTC, Takatatsu9 reviewed
Done

2023-03-01 05:49 UTC, kitazawasyogo commented
お忙しい中レビューありがとうございます。

コミット整理を行い強制Pushしました。[変更点](https://github.com/kitazawasyogo/HitAndBlow/compare/5b950ce3c41bacf61be2c03bd9b1c8939628360d..04df564d20d2381149589414ff2697de9a5ffe48)はございません。

Changes requested解決済みかと思いますがマージしてもよろしいでしょうか。

2023-03-02 00:02 UTC, Takatatsu9 approved these changes

2023-03-02 00:04 UTC, kitazawasyogo commented
ありがとうございます。
マージいたします。

2023-03-02 00:04 UTC, merged