クリアまでにかかった時間を表示する機能の追加
kitazawasyogo/HitAndBlow pull request #19
Opened 2023-03-02 04:07 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

**クリアまでにかかった時間を表示する機能の追加を行いました。**

不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-03-02 04:54 UTC, nabemasamasa reviewed
Done

2023-03-02 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Dim inputNumberOfTimes As String = game.CountInputNumber.ToString("00")
[imo] `inputNumberOfTimes `を結果表示時の文字列で書式設定する事で解決できないかな？
https://learn.microsoft.com/ja-jp/dotnet/standard/base-types/composite-formatting

例えばDateTime型を`hh:mm`で書式設定して書きたいときって`$"{DateTime.Now:hh}:{DateTime.Now:mm}"`で書けるんだけど。(String.Formatなら`Sting.Format("{0:hh}:{0:mm}", DateTime.Now)`かな)

2023-03-02 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
[Q] テスト書けませんか？0分なら省略する、1分以上掛かるなら分も表示するって、ユニットテストで書けそうだと思いますが…。

あと、機能開発時、ユニットテストを一切書いてないってことは、テストの良さをわかってない。
まず、テスト書いてから、機能開発する「テスト・ファースト」という開発手法をオススメする。

2023-03-02 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        If displayMinutes.Equals("00分") Then
[Q] `00分`という「文字列型」で比較してるのがダサいです。
clearTime.Elapsed.Minutesで判定して、Elapsedを文字列変換するのは書式設定で一括で書けない？

2023-03-02 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
これ、ミリ秒なのに「秒」がついてるの、混乱する………。

2023-03-02 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
[imo] 変数を再設定する事がないのであれば、`ReadOnly`設定した方がいい。
宣言時に再設定するつもりがないことがわかってると、後でコードリーディングして処理を追っかける際に「ここはReadOnlyついてるから再設定されないんだな」ってわかりやすい。

2023-03-02 04:54 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
[imo] オブジェクト指向プログラミングで考えるなら、一回のゲームをHitAndBlowクラス1インスタンスと見るなら、クリアタイムはHitAndBlowクラスの持ち物だと思うんだよな……。

2023-03-02 05:15 UTC, Takatatsu9 reviewed
Done

2023-03-02 05:15 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
人力テストしたからヨシ！で済ますと、今後もコード書き換える度に人力でテストすることになりますよ。
仮にこれが課題ではなく事業で改修するコードだとしたら、
数百以上あるもの毎回人力でテストするはめになりますよ。
人力だと絶対テストし忘れとかやらかしますよ。
一方テストコードは一度書いちゃえばあとはマシンが漏れなく全部やってくれるからお得。

2023-03-02 05:15 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
[IMO] `Console.WriteLine($"{displaySeconds}.{displayMilliseconds}かかりました。")`と
`Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")`の違いって
分の有無だけですよね。それ以外全部同じなのに別々に書くのって後で修正する必要が出たとき
全部書き直さなきゃいけなくなって面倒だとは思いませんか？

2023-03-02 05:15 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
[Q] 最初にあらかじめ`分`、`秒`を書いておくメリットってなんでしょうか？

2023-03-03 00:20 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
`Public ReadOnly Property clearTime As New System.Diagnostics.Stopwatch()`
プロパティにし、HitAndBlowクラス内で宣言します。

2023-03-03 00:21 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
0分なら省略する、1分以上掛かるなら分も表示するテスト追加いたします。

2023-03-03 00:34 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
考えられるメリットは特にありません。

(https://github.com/kitazawasyogo/HitAndBlow/pull/19#discussion_r1122591522)
`mm分ss.FFF秒`と表示する仕様に合わせる為このように書いていますが、ss秒とFFF秒で紛らわしいので文字列補間式で分と秒を書くように変更いたします。

2023-03-03 00:38 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +        If displayMinutes.Equals("00分") Then
「文字列型」で比較するよりも`clearTime.Elapsed.Minutes`の値で比較した方が適切（00分という文字列を判定したいのではなく分の値の有無を判定したい）だと思います。

`displayMinutes`変数を使用せずclearTime.Elapsed.Minutesで判定するようにします。

2023-03-03 00:38 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
私は、Elapsedの結果を取得できた方がいいと思う。
クリアタイムが取得できればいいんだから、StopWatchを使っている事なんて、外部は知らなくても良い。
なんとなくこれはそうなりそうな予感がするから先回りするけど、外部でそのStopWatchを動かしたり止めたりとかナンセンス、HitAndBlowが内部でゲーム開始のタイミングでStartしたり、入力に対してゲーム終了が確定したタイミングでStopすればいい。

例えば、テレビとかこの周波数ならフジテレビが映るとか、この周波数ならTBSだとかって、ユーザーは周波数を操作してチャンネルを切り替えてなんてしないよね？
カプセル化、ってそういうこと。
クラスを道具、機能として考えた際に、より使いやすいように外部からどういうメソッドを操作できると良いか、という視点で考えてみてほしい。

2023-03-03 00:49 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
補足だけど、クラスAがクラスBを使う時、カプセル化がちゃんとされてなくて、境界があいまいで密結合・過依存なほど、仕様変更とか不具合修正の際に直さないといけない範囲が増えてしまう。
クラスになるべく責務を閉じ込めて、外部に公開しているメソッドやプロパティはなるべくシンプルにするって事は、より疎結合にして修正範囲を狭めたりできる。

……これを群馬にいた頃にちゃんと教えてくれる人がいたなら私ももう少しいい状態でコードを残して行けたのになぁ……

2023-03-03 00:59 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
なぜメリットが無いことをやろうと思ったのでしょうか？

2023-03-03 01:46 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
機能追加や不具合修正の際に他の機能に影響がないか過去追加したテストを実行することを、「リグレッションテスト(回帰テスト)」と言ふ……。
設計が悪くてスパゲッティのように絡まったコードを「スパゲッティコード」というけど、テストがあったら修正の際の安心感はもはやそれは天と地の差だと思うし、リファクタリングもしやすい……。
あと忘れてたけど、お客様から何をテストしているか聞かれた際に、ハッキリ答えやすいと思う。

2023-03-03 06:36 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
理想は、クラスAを書き換えたいだけならクラスBの中身を忘れても問題ないって書き方。
クラスAだけ書き換えれば済むはずが、クラスBのロジックがクラスAにまで影響して
両方読み直して両方いじらなきゃいけないのは悪いコード。

2023-03-03 07:24 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
今`Module Main`にある（ゲームの結果表示）`DisplayHitAndBlowGame`メソッドと（ゲームクリアまでにかかった時間を表示）`DisplayClearTime`がHitAndBlowGameクラスにあれば
HitAndBlowGameクラスは、「一回分のHitAndBlowゲーム」としてしっかりとまとめられ`Module Main`は「一回分のゲーム以外の流れやその他の機能の処理」とまとめられ良い書き方。に変更する事が出来ると思います。

2023-03-06 07:42 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
最初にあらかじめ分、秒を書いたのは、`ToStoring（00分00.000秒）`の様に一回で表示したい内容を取得して書式設定を行いたっかのですが、できなかったのでやり方を変えて行ったからです。

2023-03-06 07:44 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行いました。
レビューお願いいたします。

2023-03-06 07:44 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/fff53f683ea68c6ceb1d26e183fe0a1bc95dac6d

2023-03-06 07:44 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/fff53f683ea68c6ceb1d26e183fe0a1bc95dac6d

2023-03-06 07:45 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Dim inputNumberOfTimes As String = game.CountInputNumber.ToString("00")
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/868b9fc8e55f4c735abecb61e4ad8f0e1f17feb9

2023-03-06 07:45 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/3b06539e4e7ad60c0fa670a1db46446bde341c21

2023-03-06 07:48 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/b11dee20ab09a107a9c258f53b3e8388351476b7

本来こちらのレビュー頂いた内容の修正は一つのコミットとしたかったのですが、ユニットテストを書くためにクリアタイムをコンソール出力ではなく戻り値にした為、上記のコミットに修正内容が含まれています。

2023-03-06 07:48 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +    Private clearTime As New System.Diagnostics.Stopwatch()
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/b11dee20ab09a107a9c258f53b3e8388351476b7

2023-03-06 07:48 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +        If displayMinutes.Equals("00分") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/b11dee20ab09a107a9c258f53b3e8388351476b7

2023-03-06 07:49 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Console.WriteLine($"{displayMinutes}{displaySeconds}.{displayMilliseconds}かかりました。")
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/b11dee20ab09a107a9c258f53b3e8388351476b7

2023-03-06 08:00 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
[MUST] Publicだよ

2023-03-06 08:02 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Dim displayMilliseconds As String = clearTime.Elapsed.Milliseconds.ToString("000秒")
書き終わったコードはできたーはい終わりーで済ませないで、Pushする前に一通り見直してみて
いい書き方にできないかとか考えなおしたりしてみてください。私たちに丸投げしないでください。

2023-03-06 08:22 UTC, nabemasamasa requested changes, later dismissed
NG。このミスは直近2/28。

2023-03-06 08:22 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Assert.That(actual.Length, [Is].EqualTo(14))
[Q] なんで桁数でテストしてるんですか？

2023-03-06 08:22 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        System.Threading.Thread.Sleep(30000)
一目見て、よくないテスト。
このコミットで追加したテスト達のせいで、おちおちプロジェクト単位でテストも実行できない、テストを実行する度、30秒+１分３０秒と待たされる。
そもそも…[knowledge/xUnit.md#スピード重要](http://auto3tsv132/daniel-soft/knowledge/blob/master/xUnit.md#%E3%82%B9%E3%83%94%E3%83%BC%E3%83%89%E9%87%8D%E8%A6%81)

[Q] このテストがある状態で、プロジェクト単位でRunTestしたくなくなると思うんですが、それによって起こるリスクってわかりますか？

2023-03-06 08:22 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Dim inputNumberOfTimes As String = game.CountInputNumber.ToString("00")
対応してない。

2023-03-06 23:17 UTC, Takatatsu9 reviewed
Done

2023-03-06 23:17 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> -    Private Sub DisplayHitAndBlowGame(challengeDigitsValue As String)
> クリアタイムはHitAndBlowGameクラスの持ち物である為修正

[Q] なんでクリアタイムに限定した話なのにゲームのメイン処理が移動してるんですか？

2023-03-06 23:17 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim displayTime As String = displayMinutes & ($"{displaySeconds}.{displayMilliseconds}秒かかりました。")
[Q] `displayMinutes & displaySeconds & "." & displayMilliseconds & "秒かかりました。"`と
`$"{displayMinutes}{displaySeconds}.{displayMilliseconds}秒かかりました。"`って結果同じなんですけど
なんでわざわざ混在させてるんですか？

2023-03-06 23:17 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
[Q] https://github.com/kitazawasyogo/HitAndBlow/pull/17#discussion_r1121014437 で「fixupする前提のコミットはfixupコミットで作ってください」って言って
@kitazawasyogo も 👍 つけたので肯定したと捉えてますけど、
追加されたコミット全てfixupコミットではありませんでした。
これは全てコミット整理後もそのまま残すということでいいですね？

2023-03-07 00:47 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
コメント追加します。

申し訳ありません。コーディングルール違反を見つけて貰うためにレビューして頂いている訳ではないことは理解しているつもりです。
同じ指摘ミスがないようチェックいたします。

2023-03-07 00:49 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
コメントだけじゃないよ。

2023-03-07 00:50 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Assert.That(actual.Length, [Is].EqualTo(14))
桁数でテストしても0分なら省略する、1分以上掛かるなら分も表示することをテストできると思ったからです。

`System.Threading.Thread.Sleep(30123)`
`Assert.That(actual, [Is].EqualTo("03.123秒かかりました。"))`
桁数テストではなく表示する文言でテストを行いたいのですが、テスト自体の処理にかかる時間があり、
Expected : 03.123秒かかりました。
But was : 03.125秒かかりました。となってしまうので桁数でテストしています。

2023-03-07 00:50 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
コミット整理後は、`クリアまでにかかった時間を表示する機能の追加`という一つのコミットにまとめる予定です。

fixupコミットを正しく認識できていませんでした。Push前にfixupするコミットをfixupコミットにすると思っていていました。
fixupコミットは以下の認識で正しいでしょうか？
・コミット整理時にfixupするコミット
・`fixup〇〇の為修正`というコミットコメント

2023-03-07 00:54 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        System.Threading.Thread.Sleep(30000)
プロジェクト単位でRunTestせずテストメソッドごとにテストを行うと、他のテストが変更でエラーになっていることに気づけなくなってしまい、プロジェクトのテストの価値が下がってしまいます。

2023-03-07 00:59 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> -    Private Sub DisplayHitAndBlowGame(challengeDigitsValue As String)
コミットコメントが不適切でした。

・クリアタイムの処理の移動
・ゲームの結果表示メソッドの移動
HitAndBlowGameクラスと一ゲームとする為の作業のコミットですので、クリアタイムに限定したコミットコメントではなく、`HitAndBlowGameクラスと一ゲームとする為クリアタイムとゲームの結果表示メソッドの移動`というコミットコメントに変更いたします。

2023-03-07 01:04 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
それ、誰が「これはfixupするコミットなんだ」ってわかるんですか？
その認識も間違ってます。
コミットコメントが`fixup! fixup先のコミットコメントまたはコミットハッシュ`がfixupコミットです。
というか、**fixupコミットでググれば真っ先に出てくる情報です**よ。

2023-03-07 01:06 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        System.Threading.Thread.Sleep(30000)
良いと思います。直してほしいです。

2023-03-07 01:09 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
口で言うだけなら誰にでも、それこそ幼稚園児だってできます。
社会人なら「行動で示す」ってことをやってくださいね。

2023-03-07 01:10 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Assert.That(actual.Length, [Is].EqualTo(14))
そもそも、「メッセージ表示」だけを責務として、引数Elapsedにするのはどうですか？
そうすれば、指定した時間を使って、終了時間・開始時間を宣言して、その差分でメッセージ表示するとか、
やりようはあると思う。

2023-03-07 10:04 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim displayTime As String = displayMinutes & ($"{displaySeconds}.{displayMilliseconds}秒かかりました。")
わざわざ混合させている狙いはありません。
いい書き方にできないかの考えが不足していました。

`$"{displayMinutes}{displaySeconds}.{displayMilliseconds}秒かかりました。"`の文字列補間式にまとめます。

2023-03-07 10:08 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/4270dd9b48fb8cac502cfa4ecac2937278abc721 こちらのコミットコメントを修正し、強制プッシュしました。

2023-03-07 10:10 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
テストを書くために（Public変数は外部から書き換えられてしまうので極力使用しない。）を破ってPublicにしていましたが`DisplayClearTime`メソッドの引数（Elapsed）し、メソッド内からはインスタンス変数参照しない方法に変更してPrivate変数に変更いたします。

Private変数ですが、`ゲームクリアまでにかかった時間を計測する`というコメント追加いたします。

2023-03-07 10:33 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Assert.That(actual.Length, [Is].EqualTo(14))
`DisplayClearTime`メソッドに引数Elapsedを設定します。
 Dim elapsedTime As TimeSpan = TimeSpan.FromMilliseconds(12 * 1000 + 345)で指定した時間を与える方法に変更いたします。

2023-03-07 23:53 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
https://github.com/kitazawasyogo/HitAndBlow/pull/17#discussion_r1121014437 のコメントの時点で確認せず正しく理解していないのに👍 つけたので肯定した事と、ググれば真っ先に出てくる情報をググらず確認質問してしまったことが間違いでした。
失礼いたしました。

> それとも、間違ってようが後で指摘してもらえればいいやーって無視してます？
> まさか何も考えてないなんてことはないでしょうね？

fixupコミットでググれば真っ先に出てくる情報でしたが、knowlegeのコーディングルールの様なものかと思い、knowlegeで見当たらなかったので正しい認識か確認してもし間違えていたら指摘して頂こうという甘い考えでした。

fixupコミットについて渡邊さんに口頭で説明して頂きました。

2023-03-07 23:55 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いましたのでレビューお願いいたします。

2023-03-07 23:56 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Dim inputNumberOfTimes As String = game.CountInputNumber.ToString("00")
コメントに対して対応できておりませんでした。
失礼しました。

対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/beb94c7d95fbb64b13ca9e5cbe262325f5b8eaa3

2023-03-07 23:57 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/9232520c67ab58583ea54faa5a8c0870ec2c5311

2023-03-07 23:57 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Assert.That(actual.Length, [Is].EqualTo(14))
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/9232520c67ab58583ea54faa5a8c0870ec2c5311

2023-03-07 23:57 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        System.Threading.Thread.Sleep(30000)
対応したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/9232520c67ab58583ea54faa5a8c0870ec2c5311

2023-03-07 23:58 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> -    Private Sub DisplayHitAndBlowGame(challengeDigitsValue As String)
コミットコメント修正したコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/4270dd9b48fb8cac502cfa4ecac2937278abc721

2023-03-07 23:59 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim displayTime As String = displayMinutes & ($"{displaySeconds}.{displayMilliseconds}秒かかりました。")
修正を行ったコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/af4d1f6b0dd793251e67522ce739d370bc209092

2023-03-08 00:25 UTC, nabemasamasa reviewed
Done

2023-03-08 00:25 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim displayTime As String = ($"{displayMinutes}{displaySeconds}.{displayMilliseconds}秒かかりました。")
[imo] ここまでで出てきたコードから、このメソッドはこう書ける

書式指定して0埋めするコードがこっちには修正適用されてないから、指摘の意味も込めて。
```vb
      Dim displayMinutes As String = Nothing
      If elapsedTime.Minutes <> 0 Then
          displayMinutes = $"{elapsedTime.Minutes:00}分"
      End If
      Return $"{displayMinutes}{elapsedTime.Seconds:00}.{elapsedTime.Milliseconds:00}秒かかりました。"
```

2023-03-08 00:32 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +    Public clearTime As New System.Diagnostics.Stopwatch()
コメントだけじゃなくて、外部参照できる変数なら大文字にして区別しないとです。
リーディングの際にこれが担保されてないと、いちいち参照箇所を確認したり不安が付きまといます。
前、理由を含め説明したはずですが、再度。

2023-03-08 00:34 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        If displayMinutes.Equals("00分") Then
(できれば、その修正はデカい1コミットにせず、1コミットにしてほしかったな…)

2023-03-08 00:55 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Dim displayTime As String = ($"{displayMinutes}{displaySeconds}.{displayMilliseconds}秒かかりました。")
ご指摘ありがとうございます。
対応を行ったコミットはこちらです：https://github.com/kitazawasyogo/HitAndBlow/pull/19/commits/6e22229c10e1b5f2440d457ed6f82ff888305201

2023-03-08 00:55 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行いましたのでレビューお願いいたします。

2023-03-08 01:36 UTC, nabemasamasa reviewed
Done

2023-03-08 02:49 UTC, Takatatsu9 reviewed
Done

2023-03-08 02:49 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +    Private ReadOnly clearTime As New System.Diagnostics.Stopwatch()
Privateに変えたならコメント必須ではなくなったんだけどね

2023-03-08 02:51 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> ググれば真っ先に出てくる情報をググらず確認質問してしまったことが間違いでした。

聞かれれば答えますけど、指摘するまで質問された覚え無いんですが？

2023-03-08 04:43 UTC, kitazawasyogo commented
お忙しい中レビューありがとうございます。

コミット整理を行い強制プッシュしました。[変更点](https://github.com/kitazawasyogo/HitAndBlow/compare/6e22229c10e1b5f2440d457ed6f82ff888305201..592e5af420eb1d8627f35c3ef68760c7d19bc4b7)はございません。
マージいたします。

2023-03-08 04:43 UTC, merged

2023-03-08 05:10 UTC, Takatatsu9 commented
[Q] https://github.com/kitazawasyogo/HitAndBlow/pull/17#discussion_r1121014437 で「fixupコミットじゃないコミットはfixupしないものと見てレビューします」って言って
@kitazawasyogo も 👍 つけたので肯定したと捉えてますけど、
fixupコミットでないものがfixupされました。
どうしてfixupしないコミットをfixupしたんですか？

2023-03-08 05:37 UTC, kitazawasyogo commented
ご指摘頂きfixupコミットについて教えて頂くまで正しく認識できておらずfixupする予定のコミットをixupコミットでないコミットでPushしてしまいました。
今後Fixupするコミットはfixupコミットでコミットいたします。

2023-03-08 05:44 UTC, Takatatsu9 commented
正しいfixupコミットを認識してから直すための時間はあったのにも関わらず
変えていなかったので「これはfixupしないからそのままなんだな」と思っていました。
どうしてfixupするつもり、かつその時間があったのにも関わらず放置していたんですか？

2023-03-09 04:19 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/HitAndBlow/pull/19#discussion_r1127218178

> コミット整理後は、クリアまでにかかった時間を表示する機能の追加という一つのコミットにまとめる予定です。

このコメントでfixupコミットではないコミットにしてしまった事の対応し、fixupコミットについて教えて頂いた後はfixupコミットでコミットできていたので対応できていると思い、正しいfixupコミットを認識してから直すための時間はあったのにも関わらず放置してしまいました。
失礼いたしました。