コンソールで遊べるHitAndBlowゲームを作成しました
kitazawasyogo/HitAndBlow pull request #3
Opened 2023-02-06 00:30 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

**コンソールで遊べるHitAndBlowゲームを作成しました。**

不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-02-06 04:37 UTC, Takatatsu9 reviewed
Done

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Assert.IsTrue(IsNumeric(String.Join(",", actual)))
`String.Join(",", actual)`の結果って、actualが全部0だとすると
`"0,0,0,0"`って結果になると思うんですけど、これでちゃんと`IsNumeric`Trueになるんですね

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        For count As Integer = 0 To 3
[IMO] マジックナンバーはよくないなぁ

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +                If inputValue(inputIndex) = correctValue(correctIndex) Then
[IMO] 配列なら`配列.Contains(配列に含まれてるか調べたい値)`（戻り値bool）って
できるはずだから二重For文にしなくて済むかも

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        Const CORRECT_ARRAY_LENGTH As Integer = 4
> 正解の値を重複のない値にする仕様の確認漏れがあった為変更

[IMO] これPR立てた後に追加したんじゃないなら最初から生成処理作るコミットに混ぜて欲しい。
同じPR内でこう実装したけどやっぱやーめたってやられてもレビューする価値のないものを
わざわざ時間かけてレビューさせられたって手間がかかるだけなんで。

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub 正解の値に重複がないか()
[nits] 乱数使った機能のテストって価値があるかどうか微妙なとこなんですよね…。
テストってピッタリ1万回動かせばピッタリ1万回通るかピッタリ1万回コケるかの二択になるのが
品質を担保できるテストで、偶然通るときと偶然通らないときがある乱数テストってそれが無いから…。

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            If hitNumber.Equals(4) Then
[IMO] マジックナンバー

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
[nits] 整数型は`=`で比較してもいい
[Q] それはなぜかわかりますか？

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Dim inputTestValue As String = "あいうえお"
[IMO] このテストパターンは「数字じゃない」じゃなくて「桁数が誤ってる」で
falseになっている可能性があるので不適切だと思う

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
[Q] `1.45`などの.を含めて4文字の小数点値を与えるとどうなりますか？

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ヒットした値を除外した配列()
[IMO] テスト名が何を検証したいのかわからない

2023-02-06 04:37 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Dim blowNumber As Integer = game.CountBlowValue(inputValue, hitOtherList)
なんか…手続き型プログラミングだなぁ…

2023-02-06 05:24 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub ヒットした値を除外した配列()
`ヒットした値を除外した配列をかえす`に変更いたします。

2023-02-06 05:24 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
小数点`.`や`-`、`+`を含めた4文字を入力しても想定内の入力値として判定されてしまいます。

数字のみ許可されるように処理を追加いたします。

2023-02-06 05:24 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Dim inputTestValue As String = "あいうえお"
`”あいうえ”`の4文字の数字以外の入力値に変更いたします。

2023-02-06 05:24 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
文字列型の比較の様に、大文字/小文字の区別が必要ないからだと思います。


整数型の比較は`Equals`を使用するよりも＝で比較した方が良いのでしょうか。

2023-02-06 05:24 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            If hitNumber.Equals(4) Then
定数化致します。

2023-02-06 05:25 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Const CORRECT_ARRAY_LENGTH As Integer = 4
コミット整理し、強制プッシュいたします。

不要なレビューを避けるようコミット整理するように渡邊さんに口頭で教えて頂いたにもかかわらずコミット整理時に漏れてしまいました。失礼しました。

2023-02-06 05:25 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +                If inputValue(inputIndex) = correctValue(correctIndex) Then
ご指摘ありがとうございます。
配列.Containsの方法に修正いたします。

2023-02-06 05:25 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        For count As Integer = 0 To 3
50行目の3の部分定数化致します。

2023-02-06 05:30 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
え？文字列比較って`=`だと大文字小文字曖昧一致で比較できるんですか？

私は文字列型、参照型を`=`で比較するとアドレス比較になるからって教わったんですが

2023-02-07 05:37 UTC, nabemasamasa reviewed
done

2023-02-07 05:37 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +        For count As Integer = 0 To 3
14行目も一緒の定数を参照させた方がよさそう。
同じ意味を表現している定数だし。

2023-02-07 05:37 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Dim gameTest As New HitAndBlowGame
クラスの中のメンバ変数に`Dim`はやめてください……。PrivateやPublic、ProtectedやFriendなどのアクセス修飾子を使ってください……。
メソッドやプロパティなどの中で`Dim`を使ってください……。

2023-02-07 05:37 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +                Console.WriteLine("ヒット数：" & hitNumber & "！ゲームクリア！")
[imo] 文字列結合して書くことも出来るけど、文字列補間式で埋め込んで書くこともできるよ
`$"ヒット数：{hitNumber}！ゲームクリア！"`

2023-02-07 05:37 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Console.Write("もう一度遊びますか？(Y/N)")
[Q] 「正解」メッセージ出た後、`ReadKey`があるからメッセージ後すぐに「もう一度遊びますか？」が表示されないけど、想定通りの動きですか？

2023-02-08 00:37 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +            Console.Write("もう一度遊びますか？(Y/N)")
想定通りの動きではありません。

正解メッセージ直後に「もう一度遊びますか？」が表示されないと混乱を招いてしまうと思うので修正いたします。

2023-02-08 01:26 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
小数点`.`や`-`、`+`がある場合には例外を投げる処理を追加しようと考えていましたが、IsNumericを使用して数字チェックを行うと、許容範囲が広くコードが多くなってしまいます。

前に正規表現を使用してしまうと初めて見た人などが分かりづらい....とレビューを頂きましたが今回は正規表現を使用して数字チェックを行わせていただきます。

2023-02-08 01:59 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        If Not inputValue.Length.Equals(4) OrElse Not IsNumeric(inputValue) Then
理解できていませんでした。回答し直させて下さい。
参照型は＝を使用すると同じインスタンスを参照しているか判定するのでequalsを使用し、参照先インスタンスの内容が一致するか判定
プリミティブ型（整数型）はインスタンスで扱われていないので＝で比較してもよい。

2023-02-08 02:03 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub 正解の値に重複がないか()
乱数を使った機能のテストの価値について理解出来ました。

このテストは乱数を発生させその値に重複がなければ値を追加するもので、1万回テストしたら全て通らなければいけないテストだと思います。不必要では無いと思い残させて頂きます。

2023-02-08 02:08 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        Const CORRECT_ARRAY_LENGTH As Integer = 4
後から機能追加し、２つのコミットに分かれていたものを一つにまとめました。
コミットはこちらです。[318aee5](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/318aee5acee2cfc6740280445dcd47d3d3e62b29)　

2023-02-08 02:14 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/HitAndBlow/pull/3#discussion_r1096931035
こちらのコメントの対応（後から仕様確認して追加したコミットを一つにまとめる）を行い強制プッシュしました。
[318aee5](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/318aee5acee2cfc6740280445dcd47d3d3e62b29)：まとめたコミット


[7f7f180](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/7f7f180f2372c6c5b09f2433a8cf942a857faf38)：こちらのコミットからはご指摘頂いた部分の修正になります。

お忙しいところ恐れ入りますがレビューお願いいたします。

2023-02-08 04:39 UTC, nabemasamasa requested changes, later dismissed
NG

2023-02-08 04:39 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private gameTest As New HitAndBlowGame
[Q] どう「不適切」だったんですか？なぜ不適切なのか理解出来ていて、コミットしましたか？

> クラスの中のメンバ変数の宣言方法が不適切だった為修正

2023-02-08 04:39 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +                Console.WriteLine($"ヒット数：{hitNumber}！ゲームクリア！")
> 文字列結合よりも文字列保管式を用いた方が分かりやすい為変更

Typo?
![image](https://user-images.githubusercontent.com/20126608/217434662-ed8a6178-a219-49cc-8e03-844aced3177f.png)

2023-02-08 04:39 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +        For ArrayIndex As Integer = 0 To correctValue.Length - 1
[MUST] コーディングルール違反

2023-02-08 04:42 UTC, kitazawasyogo commented on HitAndBlow/Main.vb
> +                Console.WriteLine($"ヒット数：{hitNumber}！ゲームクリア！")
Typoです。文字列補間式です。

2023-02-08 04:43 UTC, Takatatsu9 commented
[Q] どこまでがレビュー済みのコミットですか？どこからがレビューしてほしいコミットですか？
全部いちから見直さなきゃだめですか？

2023-02-08 04:48 UTC, kitazawasyogo commented
[b77f891](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/b77f89133cf00790173138932d08d3834be9ae51)こちらのコミットまではレビュー済みですが[318aee5](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/318aee5acee2cfc6740280445dcd47d3d3e62b29)こちらのコミットとは後から仕様確認して追加した部分を１つのコミットにまとめたのでレビュー対象です。

[7f7f180](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/7f7f180f2372c6c5b09f2433a8cf942a857faf38)から[b4a62f8](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/b4a62f81e74782de687b38f26f1b938d8aefead9)のコミットまでお願いいたします。

2023-02-08 04:49 UTC, kitazawasyogo commented on HitAndBlow/HitAndBlowGame.vb
> +        For ArrayIndex As Integer = 0 To correctValue.Length - 1
失礼いたしました。ローカル変数の命名規則に従い修正いたします。

2023-02-08 05:00 UTC, kitazawasyogo commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private gameTest As New HitAndBlowGame
`gameTest `はローカル変数ではなくメンバー変数ですが、[アクセス修飾子]変数名 AsではなくDimを使用してしまった為、宣言方法が不適切でした。　

2023-02-08 05:10 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private gameTest As New HitAndBlowGame
良いと思います。
重箱の隅をつつくようだけど、メンバ変数はクラスの持つ変数やプロパティを指すので、「クラスの中の」はいらなかったかな……。ちょっと冗長。

2023-02-08 05:25 UTC, kitazawasyogo commented
@nabemasamasa　[e3ef6ea](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/e3ef6eaa0bd2b889691eb9a09ef71948b723ac13)のコミットコメントと[95d82f8](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/95d82f8b98d2bd6d6056213c8e1c38f1e5a10b11)　をレビューお願いいたします。


@Takatatsu9　[318aee5](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/318aee5acee2cfc6740280445dcd47d3d3e62b29)こちらのコミットと
[7f7f180](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/7f7f180f2372c6c5b09f2433a8cf942a857faf38)　～　[95d82f8](https://github.com/kitazawasyogo/HitAndBlow/pull/3/commits/95d82f8b98d2bd6d6056213c8e1c38f1e5a10b11)　のレビューお願いいたします。

2023-02-08 05:28 UTC, nabemasamasa reviewed
Done

2023-02-09 02:23 UTC, Takatatsu9 reviewed
Done

2023-02-09 02:27 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    <Test()> Public Sub 入力値に小数点が含まれる場合()
[IMO] 含まれる場合、何？
同じPRで`[IMO] テスト名が何を検証したいのかわからない`という指摘をしたばかりですが、
もう忘れてしまいましたか。

2023-02-09 02:52 UTC, kitazawasyogo commented
> [IMO] 含まれる場合、何？
> 同じPRで[IMO] テスト名が何を検証したいのかわからないという指摘をしたばかりですが、
> もう忘れてしまいましたか。

何を検証するのか分かりやすいテスト名に修正しました。
他のテスト名も一貫性を持たせ修正を行いました。

レビューお願いいたします。

2023-02-09 02:54 UTC, Takatatsu9 reviewed
Done

2023-02-09 03:01 UTC, nabemasamasa reviewed
Done

2023-02-09 03:06 UTC, nabemasamasa commented
PRにコメントするんじゃなくて、レビューコメントに対して「修正しました」報告してほしい…………。
指摘に対してそれを修正したのかどうか、コミットの内容と比較しながらいちいち解決済みか確認するの面倒なので……。

あと、コメントの右上「・・・」にCopyLinkとか、QuateReplyとかあるので、確認してみると良いかも知れません。

2023-02-09 23:23 UTC, kitazawasyogo commented
レビューありがとうございます。
コミット整理を行い強制プッシュしました[変更点](https://github.com/kitazawasyogo/HitAndBlow/compare/063df8e3a61d9f409170e2cc6961681586bd3ce4..cf0cbb4c46a63cb20839894d238aa4391de207c5)はございません。

マージいたします。

2023-02-09 23:24 UTC, merged